# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jan/workspace/wotreplay-parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jan/workspace/wotreplay-parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/workspace/wotreplay-parser/CMakeFiles /home/jan/workspace/wotreplay-parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jan/workspace/wotreplay-parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wotreplay-parser

# Build rule for target.
wotreplay-parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wotreplay-parser
.PHONY : wotreplay-parser

# fast build rule for target.
wotreplay-parser/fast:
	$(MAKE) -f CMakeFiles/wotreplay-parser.dir/build.make CMakeFiles/wotreplay-parser.dir/build
.PHONY : wotreplay-parser/fast

#=============================================================================
# Target rules for targets named jsoncpp

# Build rule for target.
jsoncpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsoncpp
.PHONY : jsoncpp

# fast build rule for target.
jsoncpp/fast:
	$(MAKE) -f CMakeFiles/jsoncpp.dir/build.make CMakeFiles/jsoncpp.dir/build
.PHONY : jsoncpp/fast

#=============================================================================
# Target rules for targets named wotreplay

# Build rule for target.
wotreplay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wotreplay
.PHONY : wotreplay

# fast build rule for target.
wotreplay/fast:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/build
.PHONY : wotreplay/fast

ext/jsoncpp/src/jsoncpp.o: ext/jsoncpp/src/jsoncpp.cpp.o

.PHONY : ext/jsoncpp/src/jsoncpp.o

# target to build an object file
ext/jsoncpp/src/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/jsoncpp.dir/build.make CMakeFiles/jsoncpp.dir/ext/jsoncpp/src/jsoncpp.cpp.o
.PHONY : ext/jsoncpp/src/jsoncpp.cpp.o

ext/jsoncpp/src/jsoncpp.i: ext/jsoncpp/src/jsoncpp.cpp.i

.PHONY : ext/jsoncpp/src/jsoncpp.i

# target to preprocess a source file
ext/jsoncpp/src/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/jsoncpp.dir/build.make CMakeFiles/jsoncpp.dir/ext/jsoncpp/src/jsoncpp.cpp.i
.PHONY : ext/jsoncpp/src/jsoncpp.cpp.i

ext/jsoncpp/src/jsoncpp.s: ext/jsoncpp/src/jsoncpp.cpp.s

.PHONY : ext/jsoncpp/src/jsoncpp.s

# target to generate assembly for a file
ext/jsoncpp/src/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/jsoncpp.dir/build.make CMakeFiles/jsoncpp.dir/ext/jsoncpp/src/jsoncpp.cpp.s
.PHONY : ext/jsoncpp/src/jsoncpp.cpp.s

src/animation_writer.o: src/animation_writer.cpp.o

.PHONY : src/animation_writer.o

# target to build an object file
src/animation_writer.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/animation_writer.cpp.o
.PHONY : src/animation_writer.cpp.o

src/animation_writer.i: src/animation_writer.cpp.i

.PHONY : src/animation_writer.i

# target to preprocess a source file
src/animation_writer.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/animation_writer.cpp.i
.PHONY : src/animation_writer.cpp.i

src/animation_writer.s: src/animation_writer.cpp.s

.PHONY : src/animation_writer.s

# target to generate assembly for a file
src/animation_writer.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/animation_writer.cpp.s
.PHONY : src/animation_writer.cpp.s

src/arena.o: src/arena.cpp.o

.PHONY : src/arena.o

# target to build an object file
src/arena.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/arena.cpp.o
.PHONY : src/arena.cpp.o

src/arena.i: src/arena.cpp.i

.PHONY : src/arena.i

# target to preprocess a source file
src/arena.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/arena.cpp.i
.PHONY : src/arena.cpp.i

src/arena.s: src/arena.cpp.s

.PHONY : src/arena.s

# target to generate assembly for a file
src/arena.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/arena.cpp.s
.PHONY : src/arena.cpp.s

src/class_heatmap_writer.o: src/class_heatmap_writer.cpp.o

.PHONY : src/class_heatmap_writer.o

# target to build an object file
src/class_heatmap_writer.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/class_heatmap_writer.cpp.o
.PHONY : src/class_heatmap_writer.cpp.o

src/class_heatmap_writer.i: src/class_heatmap_writer.cpp.i

.PHONY : src/class_heatmap_writer.i

# target to preprocess a source file
src/class_heatmap_writer.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/class_heatmap_writer.cpp.i
.PHONY : src/class_heatmap_writer.cpp.i

src/class_heatmap_writer.s: src/class_heatmap_writer.cpp.s

.PHONY : src/class_heatmap_writer.s

# target to generate assembly for a file
src/class_heatmap_writer.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/class_heatmap_writer.cpp.s
.PHONY : src/class_heatmap_writer.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/heatmap_writer.o: src/heatmap_writer.cpp.o

.PHONY : src/heatmap_writer.o

# target to build an object file
src/heatmap_writer.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/heatmap_writer.cpp.o
.PHONY : src/heatmap_writer.cpp.o

src/heatmap_writer.i: src/heatmap_writer.cpp.i

.PHONY : src/heatmap_writer.i

# target to preprocess a source file
src/heatmap_writer.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/heatmap_writer.cpp.i
.PHONY : src/heatmap_writer.cpp.i

src/heatmap_writer.s: src/heatmap_writer.cpp.s

.PHONY : src/heatmap_writer.s

# target to generate assembly for a file
src/heatmap_writer.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/heatmap_writer.cpp.s
.PHONY : src/heatmap_writer.cpp.s

src/image_util.o: src/image_util.cpp.o

.PHONY : src/image_util.o

# target to build an object file
src/image_util.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_util.cpp.o
.PHONY : src/image_util.cpp.o

src/image_util.i: src/image_util.cpp.i

.PHONY : src/image_util.i

# target to preprocess a source file
src/image_util.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_util.cpp.i
.PHONY : src/image_util.cpp.i

src/image_util.s: src/image_util.cpp.s

.PHONY : src/image_util.s

# target to generate assembly for a file
src/image_util.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_util.cpp.s
.PHONY : src/image_util.cpp.s

src/image_writer.o: src/image_writer.cpp.o

.PHONY : src/image_writer.o

# target to build an object file
src/image_writer.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_writer.cpp.o
.PHONY : src/image_writer.cpp.o

src/image_writer.i: src/image_writer.cpp.i

.PHONY : src/image_writer.i

# target to preprocess a source file
src/image_writer.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_writer.cpp.i
.PHONY : src/image_writer.cpp.i

src/image_writer.s: src/image_writer.cpp.s

.PHONY : src/image_writer.s

# target to generate assembly for a file
src/image_writer.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/image_writer.cpp.s
.PHONY : src/image_writer.cpp.s

src/json_writer.o: src/json_writer.cpp.o

.PHONY : src/json_writer.o

# target to build an object file
src/json_writer.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/json_writer.cpp.o
.PHONY : src/json_writer.cpp.o

src/json_writer.i: src/json_writer.cpp.i

.PHONY : src/json_writer.i

# target to preprocess a source file
src/json_writer.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/json_writer.cpp.i
.PHONY : src/json_writer.cpp.i

src/json_writer.s: src/json_writer.cpp.s

.PHONY : src/json_writer.s

# target to generate assembly for a file
src/json_writer.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/json_writer.cpp.s
.PHONY : src/json_writer.cpp.s

src/logger.o: src/logger.cpp.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay-parser.dir/build.make CMakeFiles/wotreplay-parser.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay-parser.dir/build.make CMakeFiles/wotreplay-parser.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay-parser.dir/build.make CMakeFiles/wotreplay-parser.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/packet.o: src/packet.cpp.o

.PHONY : src/packet.o

# target to build an object file
src/packet.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet.cpp.o
.PHONY : src/packet.cpp.o

src/packet.i: src/packet.cpp.i

.PHONY : src/packet.i

# target to preprocess a source file
src/packet.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet.cpp.i
.PHONY : src/packet.cpp.i

src/packet.s: src/packet.cpp.s

.PHONY : src/packet.s

# target to generate assembly for a file
src/packet.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet.cpp.s
.PHONY : src/packet.cpp.s

src/packet_reader_80.o: src/packet_reader_80.cpp.o

.PHONY : src/packet_reader_80.o

# target to build an object file
src/packet_reader_80.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet_reader_80.cpp.o
.PHONY : src/packet_reader_80.cpp.o

src/packet_reader_80.i: src/packet_reader_80.cpp.i

.PHONY : src/packet_reader_80.i

# target to preprocess a source file
src/packet_reader_80.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet_reader_80.cpp.i
.PHONY : src/packet_reader_80.cpp.i

src/packet_reader_80.s: src/packet_reader_80.cpp.s

.PHONY : src/packet_reader_80.s

# target to generate assembly for a file
src/packet_reader_80.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/packet_reader_80.cpp.s
.PHONY : src/packet_reader_80.cpp.s

src/parser.o: src/parser.cpp.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/rule.o: src/rule.cpp.o

.PHONY : src/rule.o

# target to build an object file
src/rule.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/rule.cpp.o
.PHONY : src/rule.cpp.o

src/rule.i: src/rule.cpp.i

.PHONY : src/rule.i

# target to preprocess a source file
src/rule.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/rule.cpp.i
.PHONY : src/rule.cpp.i

src/rule.s: src/rule.cpp.s

.PHONY : src/rule.s

# target to generate assembly for a file
src/rule.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/rule.cpp.s
.PHONY : src/rule.cpp.s

src/tank.o: src/tank.cpp.o

.PHONY : src/tank.o

# target to build an object file
src/tank.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tank.cpp.o
.PHONY : src/tank.cpp.o

src/tank.i: src/tank.cpp.i

.PHONY : src/tank.i

# target to preprocess a source file
src/tank.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tank.cpp.i
.PHONY : src/tank.cpp.i

src/tank.s: src/tank.cpp.s

.PHONY : src/tank.s

# target to generate assembly for a file
src/tank.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tank.cpp.s
.PHONY : src/tank.cpp.s

src/tinyxml2.o: src/tinyxml2.cpp.o

.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i

.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s

.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/wotreplay.dir/build.make CMakeFiles/wotreplay.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... wotreplay-parser"
	@echo "... rebuild_cache"
	@echo "... jsoncpp"
	@echo "... wotreplay"
	@echo "... ext/jsoncpp/src/jsoncpp.o"
	@echo "... ext/jsoncpp/src/jsoncpp.i"
	@echo "... ext/jsoncpp/src/jsoncpp.s"
	@echo "... src/animation_writer.o"
	@echo "... src/animation_writer.i"
	@echo "... src/animation_writer.s"
	@echo "... src/arena.o"
	@echo "... src/arena.i"
	@echo "... src/arena.s"
	@echo "... src/class_heatmap_writer.o"
	@echo "... src/class_heatmap_writer.i"
	@echo "... src/class_heatmap_writer.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/heatmap_writer.o"
	@echo "... src/heatmap_writer.i"
	@echo "... src/heatmap_writer.s"
	@echo "... src/image_util.o"
	@echo "... src/image_util.i"
	@echo "... src/image_util.s"
	@echo "... src/image_writer.o"
	@echo "... src/image_writer.i"
	@echo "... src/image_writer.s"
	@echo "... src/json_writer.o"
	@echo "... src/json_writer.i"
	@echo "... src/json_writer.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/packet.o"
	@echo "... src/packet.i"
	@echo "... src/packet.s"
	@echo "... src/packet_reader_80.o"
	@echo "... src/packet_reader_80.i"
	@echo "... src/packet_reader_80.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/rule.o"
	@echo "... src/rule.i"
	@echo "... src/rule.s"
	@echo "... src/tank.o"
	@echo "... src/tank.i"
	@echo "... src/tank.s"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

