
IN ?= in/
BUILD ?= build/
OUT ?= out/
SOURCES = $(wildcard $(IN)*.wotbreplay)
VIDEOS = $(addprefix $(OUT),$(patsubst %.wotbreplay, %.mp4, $(notdir $(SOURCES))))
VIDEOS_DEBUG = $(addprefix $(OUT),$(patsubst %.wotbreplay, %-debug.mp4, $(notdir $(SOURCES))))
PARSER ?= ./bin/wotreplay-parser
SKIP ?= 30
MAP_SIZE ?= 300
FRAME_RATE ?= 20

.PRECIOUS: %.mp4
.INTERMEDIATE: %-input
.phony: clean

default: videos

all: videos

all-debug: videos-debug

videos: $(VIDEOS)

videos-debug: $(VIDEOS_DEBUG)

$(BUILD)%.input/data.wotreplay : $(IN)%.wotbreplay | $(BUILD)
	unzip -o $< -d $(dir $@)

$(BUILD)%.gif :  $(BUILD)%.input/data.wotreplay
	$(PARSER) --parse --type gif --raw-images-path $(subst .gif,.raw,$@) --input $< --output $@ --skip $(SKIP) --blitz --map-size $(MAP_SIZE) --frame-rate $(FRAME_RATE)

$(OUT)%.mp4 : $(BUILD)%.gif | $(OUT)
	ffmpeg -f image2 -r 10 -pattern_type glob -i "$(subst .gif,.raw,$<)/frame-*.png" -vcodec libx264 -crf 22 -y $@
	rm -rf "$(subst .mp4,.raw,$@)" $<

$(BUILD)%-debug.gif :  $(BUILD)%.input/data.wotreplay | $(BUILD)
	$(PARSER) --parse --type gif --raw-images-path $(subst .gif,.raw,$@) --input $< --output $@ --skip $(SKIP) --blitz --map-size $(MAP_SIZE) --frame-rate $(FRAME_RATE) --debug

$(OUT)%-debug.mp4 : $(BUILD)%-debug.gif | $(OUT)
	ffmpeg -f image2 -r 10 -pattern_type glob -i "$(subst .gif,.raw,$<)/frame-*.png" -vcodec libx264 -crf 22 -y $@
	rm -rf "$(subst .mp4,.raw,$@)" $<

clean:
	rm -rf *.input *.raw *.gif

$(BUILD) $(OUT):
	mkdir -p $@
